config/routes.rb
Anunciar2::Application.routes.draw do
  resources :banners

  resources :imagems

  resources :imovels

  devise_for :users
  
  match 'imovels/dynamic_cidades/:id' => 'imovels#dynamic_cidades'
  match 'imovels/dynamic_bairros/:id' => 'imovels#dynamic_bairros'
  

  root :to => 'home#index'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  belongs_to :imovel
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  #before_filter :validate_roles
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banners }
    end
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
    @banner = Banner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/new
  # GET /banners/new.json
  def new
    @banner = Banner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banner }
    end
  end

  # GET /banners/1/edit
  def edit
    @banner = Banner.find(params[:id])
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(params[:banner])

    respond_to do |format|
      if @banner.save
        format.html { redirect_to @banner, notice: 'Banner was successfully created.' }
        format.json { render json: @banner, status: :created, location: @banner }
      else
        format.html { render action: "new" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banners/1
  # PUT /banners/1.json
  def update
    @banner = Banner.find(params[:id])

    respond_to do |format|
      if @banner.update_attributes(params[:banner])
        format.html { redirect_to @banner, notice: 'Banner was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy

    respond_to do |format|
      format.html { redirect_to banners_url }
      format.json { head :ok }
    end
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= simple_form_for(@banner) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :imovel %>
    <%= f.input :inicio %>
    <%= f.input :fim %>
    <%= f.input :ativo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editando Banner Principal</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @banner %> |
<%= link_to 'Voltar', banners_path %>

app/views/banners/index.html.erb
<h1>Linstando Banners</h1>

<table class="table table-condensed">
	<thead>
		<tr>
		    <th>Imovel</th>
		    <th>Inicio</th>
		    <th>Fim</th>
		    <th>Ativo</th>
		    <th></th>
		    <th></th>
		    <th></th>
		</tr>
	</thead>

	<tbody>
		<% @banners.each do |banner| %>
		  <tr>
		    <td><%= banner.imovel %></td>
		    <td><%= banner.inicio %></td>
		    <td><%= banner.fim %></td>
		    <td><%= banner.ativo %></td>
		    <td><%= link_to 'Visualizar', banner %></td>
		    <td><%= link_to 'Editar', edit_banner_path(banner) %></td>
		    <td><%= link_to 'Deletar', banner, confirm: 'Você tem certeza?', method: :delete %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

<br />

<%= link_to 'Novo Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1>Novo Banner</h1>

<%= render 'form' %>

<%= link_to 'Voltar', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Imovel:</b>
  <%= @banner.imovel %>
</p>

<p>
  <b>Inicio:</b>
  <%= @banner.inicio %>
</p>

<p>
  <b>Fim:</b>
  <%= @banner.fim %>
</p>

<p>
  <b>Ativo:</b>
  <%= @banner.ativo %>
</p>


<%= link_to 'Editar', edit_banner_path(@banner) %> |
<%= link_to 'Voltar', banners_path %>