config/routes.rb
Anunciar2::Application.routes.draw do
  resources :banners

  resources :imagems

  resources :imovels

  devise_for :users
  
  match 'imovels/dynamic_cidades/:id' => 'imovels#dynamic_cidades'
  match 'imovels/dynamic_bairros/:id' => 'imovels#dynamic_bairros'
  

  root :to => 'home#index'

end

app/models/imagem.rb
class Imagem < ActiveRecord::Base
  belongs_to :imovel
  attr_accessible :arquivo, :nome, :imovel_id, :capa
  mount_uploader :arquivo, ImagemUploader
  
  validates_presence_of :nome, :arquivo, :imovel
  
  before_update :set_capa_blank
  
  def set_capa_blank
    unless self.imovel_id.blank?
      Imagem.where('imovel_id = ? and capa = ?', self.imovel_id, true).update_all(:capa => 0)
    end
  end
  
end

app/controllers/imagems_controller.rb
class ImagemsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_user!
  
  def authorize_user!
    unless current_user.has_role? "root"
      true
    end
  end
  
  # GET /imagems
  # GET /imagems.json
  def index
    @imagems = Imagem.where(:imovel_id => current_user.imovels {|i| i.id})

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @imagems }
    end
  end

  # GET /imagems/1
  # GET /imagems/1.json
  def show
    @imagem = Imagem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @imagem }
    end
  end

  # GET /imagems/new
  # GET /imagems/new.json
  def new
    @imagem = Imagem.new
    @imagem.imovel = Imovel.find(params[:id]) if params[:id]
    
    # unless @imagem.imovel
      # return redirect_to imagems_path
    # end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @imagem }
    end
  end

  # GET /imagems/1/edit
  def edit
    @imagem = Imagem.find(params[:id])
  end

  # POST /imagems
  # POST /imagems.json
  def create
    @imagem = Imagem.new(params[:imagem])

    respond_to do |format|
      if @imagem.save
        format.html { redirect_to new_imagem_path(:id => @imagem.imovel.id), notice: 'Imagem criada com sucesso.'}
        format.json { render json: @imagem, status: :created, location: @imagem }
      else
        format.html { render action: "new" }
        format.json { render json: @imagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /imagems/1
  # PUT /imagems/1.json
  def update
    @imagem = Imagem.find(params[:id])

    respond_to do |format|
      if @imagem.update_attributes(params[:imagem])
        format.html { redirect_to @imagem, notice: 'Imagem was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @imagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imagems/1
  # DELETE /imagems/1.json
  def destroy
    @imagem = Imagem.find(params[:id])
    @imagem.destroy

    respond_to do |format|
      format.html { redirect_to imagems_url }
      format.json { head :ok }
    end
  end
end

app/helpers/imagems_helper.rb
module ImagemsHelper
end

app/views/imagems/_form.html.erb
<%= simple_form_for(@imagem, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :arquivo, :as => 'file' %>
    <%= f.input :nome, :hint => 'Ex: sala, quarto...' %>
    <%= f.input :capa %>
    <%= f.association :imovel %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/imagems/_gallery_new.html.erb
<%if @imagem.imovel%>
	<ul class="thumbnails">
		<% for imagem in @imagem.imovel.imagems %>
		    <li class="span3">
			    <a href="#" class="thumbnail">
			    	<%= image_tag imagem.arquivo_url(:thumb), :size => "200x200"  %>
			    </a>
			    <center>
			    	<h3><%= imagem.nome%></h3>
					<div class="actions">
						<%= link_to "editar", edit_imagem_path(imagem) %> |
						<%= link_to "remover", imagem, :confirm => 'Are you sure?', :method => :delete %>
					</div>
				</center>
		    </li>
	    <%end%>
    </ul>
<%end%>

app/views/imagems/edit.html.erb
<h1>Editando Imagem</h1>
<br />

<div class="row">
	<div class="span8">
		<%= render 'form' %>
	</div>
	<div class="span4">
		<ul class="thumbnails">
		    <li class="span3">
			    <a href="#" class="thumbnail">
			    	<%= image_tag @imagem.arquivo_url(:thumb), :size => "200x200"  %>
			    </a>
			    <center>
			    	<h3><%= @imagem.nome%></h3>
				</center>
		    </li>
    	</ul>
	</div>
</div>

<%= link_to 'Visualizar', @imagem %> |
<%= link_to 'Voltar', imagems_path %>

app/views/imagems/index.html.erb
<h1>Listando Imagens</h1>
<br>

<table class="table table-condensed">
	<thead>
		<tr>
			<th>Arquivo</th>
			<th>Nome</th>
			<th>Capa</th>
			<th>Imovel</th>
			<th></th>
			<th></th>
			<th></th>
		</tr>
	</thead>
<% @imagems.each do |imagem| %>
  <tbody>
	  <tr align="center">
	    <td>
	    	<ul class="thumbnails">
			    <li class="span2">
				    <a href="#" class="thumbnail">
				    	<%= image_tag imagem.arquivo_url(:thumb), :size => "70x70"  %>
				    </a>
			    </li>
	    	</ul>
	    </td>
	    <td><%= imagem.nome %></td>
	    <td><%= imagem.capa %></td>
	    <td><%= imagem.imovel.id.to_s + "-" + imagem.imovel.titulo %></td>
	    <td><%= link_to 'Show', imagem %></td>
	    <td><%= link_to 'Edit', edit_imagem_path(imagem) %></td>
	    <td><%= link_to 'Destroy', imagem, confirm: 'Are you sure?', method: :delete %></td>
	  </tr>
  </tbody>
<% end %>
</table>

<br />

<%= link_to 'Nova Imagem', new_imagem_path %>

app/views/imagems/new.html.erb
<h1>Nova Imagem</h1>
<br>

<%= render 'form' %>

<%= render 'gallery_new' %>

<%= link_to 'Voltar', imagems_path %>

app/views/imagems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Arquivo:</b>
  <%= @imagem.arquivo %>
</p>

<p>
  <b>Nome:</b>
  <%= @imagem.nome %>
</p>

<p>
  <b>Capa:</b>
  <%= @imagem.capa %>
</p>

<p>
  <b>Imovel:</b>
  <%= @imagem.imovel %>
</p>


<%= link_to 'Editar', edit_imagem_path(@imagem) %> |
<%= link_to 'Voltar', imagems_path %>