config/routes.rb
Anunciar2::Application.routes.draw do
  resources :banners

  resources :imagems

  resources :imovels

  devise_for :users
  
  match 'imovels/dynamic_cidades/:id' => 'imovels#dynamic_cidades'
  match 'imovels/dynamic_bairros/:id' => 'imovels#dynamic_bairros'
  

  root :to => 'home#index'

end

app/models/imovel.rb
class Imovel < ActiveRecord::Base
  attr_accessible :user_id, :estado_id, :cidade_id, :bairro_id, :tipo_id, :pretensao_id, :situacao, :endereco, :quarto, 
                  :suite, :banheiro, :sala, :cozinha, :dependencia, :area, :posicao, :garagem, :piscina,
                  :valor, :condominio, :descricao, :titulo
  
  belongs_to :user
  belongs_to :estado
  belongs_to :cidade
  belongs_to :bairro
  belongs_to :tipo
  belongs_to :pretensao
  has_many :imagems, :dependent => :destroy
  has_many :banners, :dependent => :destroy
  
  validates_presence_of :user, :estado, :cidade, :bairro, :tipo, :pretensao, :situacao, :titulo, :valor, :descricao
  #validates_numericality_of :endereco, :if => Proc.new { |imovel| imovel.endereco.length > 0 }
  validates :quarto, :suite, :banheiro, :sala, :cozinha, :dependencia, :area, :numericality => true, :allow_blank => true
  validates :garagem, :piscina, :valor, :condominio, :numericality => true, :allow_blank => true
  
  before_validation(:on => :create) do
    self.valor = self.valor.real.to_f
  end
  
  def to_s
    titulo
  end
  
  def capa
    self.imagems.where(:capa => true).first
  end
  
end

app/controllers/imovels_controller.rb
class ImovelsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :new, :edit, :update]
  
  # GET /imovels
  # GET /imovels.json
  def index
    @imovels = Imovel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @imovels }
    end
  end

  # GET /imovels/1
  # GET /imovels/1.json
  def show
    @imovel = Imovel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @imovel }
    end
  end

  # GET /imovels/new
  # GET /imovels/new.json
  def new
    @imovel = Imovel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @imovel }
    end
  end

  # GET /imovels/1/edit
  def edit
    @imovel = Imovel.find(params[:id])
  end

  # POST /imovels
  # POST /imovels.json
  def create
    @imovel = Imovel.new(params[:imovel])
    puts params[:imovel]
    #@imovel.estado = Estado.find(params[:imovel][:estado_id]) if params[:imovel][:estado_id]
    @imovel.user = current_user 

    respond_to do |format|
      if @imovel.save
        format.html { redirect_to new_imagem_path(:id=>@imovel.id), notice: 'Imovel criado com sucesso.'}
        format.json { render json: @imovel, status: :created, location: @imovel }
      else
        format.html { render action: "new" }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /imovels/1
  # PUT /imovels/1.json
  def update
    @imovel = Imovel.find(params[:id])

    respond_to do |format|
      if @imovel.update_attributes(params[:imovel])
        format.html { redirect_to @imovel, notice: 'Imovel was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @imovel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imovels/1
  # DELETE /imovels/1.json
  def destroy
    @imovel = Imovel.find(params[:id])
    @imovel.destroy

    respond_to do |format|
      format.html { redirect_to imovels_url }
      format.json { head :ok }
    end
  end
  
  def dynamic_cidades
    @cidades = Cidade.find_all_by_estado_id(params[:id])
    respond_to do |format|
      format.js
    end
  end
  
  def dynamic_bairros
    @bairros = Bairro.find_all_by_cidade_id(params[:id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/imovels_helper.rb
module ImovelsHelper
end

app/views/imovels/_form.html.erb
<br clear="all" \>
<%= simple_form_for(@imovel, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :estado %>
    
	<%unless @imovel.estado.blank? %>
		<%= f.association :cidade, :collection => @imovel.estado.cidades(:order => 'nome') %>
		<%unless @imovel.estado.cidade.blank? %>
			<%= f.association :bairro, :collection => @imovel.estado.cidades.where(:id => params[:imovel][:cidade_id]).first.bairros(:order => 'nome') %>
		<%else%>
			<%= f.association :bairro, :collection => [] %>
		<%end%>
	<%else%>
		<%= f.association :cidade, :collection => [] %>
		<%= f.association :bairro, :collection => [] %>
	<%end%>

    <%= f.association :tipo %>
    <%= f.association :pretensao %>
    <%= f.input :titulo, :hint => 'nome do empreendimento' %>
    <%= f.input :situacao, :collection => ["Novo", "Usado"], :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :endereco, :hint => 'visível apenas para o anunciante!' %>
    <%= f.input :quarto, :collection => 1..10, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :suite, :collection => 1..5, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :banheiro, :collection => 1..7, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :sala, :collection => 1..5, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :cozinha, :collection => 1..5, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :dependencia, :collection => 1..3, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :area %>
    <%= f.input :posicao, :hint => 'Ex: nascente/sul, nascente/norte' %>
    <%= f.input :garagem, :collection => 1..5, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :piscina, :collection => 1..5, :as => :radio_buttons, :item_wrapper_class => 'inline' %>
    <%= f.input :valor %>
    <%= f.input :condominio %>
    <%= f.input :descricao %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/imovels/_show_attrs.html.erb
<!-- <p>
  <b>User:</b>
  <%= @imovel.user %>
</p> -->
<%unless @imovel.estado.blank?%>
	<p>
	  <b>Estado:</b>
	  <%= @imovel.estado %>
	</p>
<%end%>

<%unless @imovel.cidade.blank? %>
	<p>
	  <b>Cidade:</b>
	  <%= @imovel.cidade %>
	</p>
<%end%>

<%unless @imovel.bairro.blank? %>
	<p>
	  <b>Bairro:</b>
	  <%= @imovel.bairro %>
	</p>
<%end%>

<%unless @imovel.tipo.blank? %>
	<p>
	  <b>Tipo:</b>
	  <%= @imovel.tipo %>
	</p>
<%end%>

<%unless @imovel.pretensao.blank? %>
	<p>
	  <b>Pretensao:</b>
	  <%= @imovel.pretensao %>
	</p>
<%end%>

<%unless @imovel.situacao.blank? %>
	<p>
	  <b>Situacao:</b>
	  <%= @imovel.situacao %>
	</p>
<%end%>

<%unless @imovel.endereco.blank? %>
	<p>
	  <b>Endereco:</b>
	  <%= @imovel.endereco %>
	</p>
<%end%>

<%unless @imovel.quarto.blank? %>
	<p>
	  <b>Quarto:</b>
	  <%= @imovel.quarto %>
	</p>
<%end%>

<%unless @imovel.suite.blank? %>
	<p>
	  <b>Suite:</b>
	  <%= @imovel.suite %>
	</p>
<%end%>

<%unless @imovel.banheiro.blank? %>
	<p>
	  <b>Banheiro:</b>
	  <%= @imovel.banheiro %>
	</p>
<%end%>

<%unless @imovel.sala.blank? %>
	<p>
	  <b>Sala:</b>
	  <%= @imovel.sala %>
	</p>
<%end%>

<%unless @imovel.cozinha.blank? %>
	<p>
	  <b>Cozinha:</b>
	  <%= @imovel.cozinha %>
	</p>
<%end%>

<%unless @imovel.dependencia.blank? %>
	<p>
	  <b>Dependencia:</b>
	  <%= @imovel.dependencia %>
	</p>
<%end%>	

<%unless @imovel.area.blank? %>
	<p>
	  <b>Area:</b>
	  <%= @imovel.area %>
	</p>
<%end%>

<%unless @imovel.posicao.blank? %>
	<p>
	  <b>Posicao:</b>
	  <%= @imovel.posicao %>
	</p>
<%end%>

<%unless @imovel.garagem.blank? %>
	<p>
	  <b>Garagem:</b>
	  <%= @imovel.garagem %>
	</p>
<%end%>

<%unless @imovel.piscina.blank? %>
	<p>
	  <b>Piscina:</b>
	  <%= @imovel.piscina %>
	</p>
<%end%>

<%unless @imovel.condominio.blank? %>
	<p>
	  <b>Valor:</b>
	  <%= @imovel.condominio %>
	</p>
<%end%>

<%unless @imovel.condominio.blank? %>
	<p>
	  <b>Condominio:</b>
	  <%= @imovel.condominio %>
	</p>
<%end%>

<%unless @imovel.descricao.blank? %>
	<p>
	  <b>Descricao:</b>
	  <%= @imovel.descricao %>
	</p>
<%end%>

app/views/imovels/_show_gallery.html.erb
<div id="page">
	<div id="container" class="containergallery">
		<h1>Imagens de <%=@imovel.titulo%></h1>

		<!-- Start Advanced Gallery Html Containers -->
		<div id="gallery">
			<div id="controls" class="controls"></div>
			<div class="slideshow-container">
				<div id="loading" class="loader"></div>
				<div id="slideshow" class="slideshow"></div>
			</div>
			<div id="caption" class="caption-container"></div>
		</div>
		<div id="thumbs" class="navigation">
			<ul class="thumbs noscript">
				<%@imovel.imagems.each do |i|%>
					<%url = i.arquivo.url%>
					<%url = 'http://farm4.static.flickr.com/3261/2538183196_8baf9a8015_s.jpg' if !url%>
					<li class="imagem">
						<a class="thumb" name="leaf" href="<%=i.arquivo.thumb.url%>" title="Title #0">
							<%= image_tag url, :alt => 'Title #0', :size => "75x75" %>
						</a>
						<div class="caption">
							<div class="download">
								<a href="<%=i.arquivo.url%>">Download Original</a>
							</div>
							<div class="image-title"><%=i.nome%></div>
							<div class="image-desc"><%=i.imovel.descricao%></div>
						</div>
					</li>
				<%end%>
			</ul>
		</div>
		<div style="clear: both;"></div>
	</div>
</div>
<div id="footer">&copy; 2009 Trent Foley</div>

app/views/imovels/dynamic_bairros.js.erb
$('#imovel_bairro_id').empty();
<% for bairro in @bairros %>
	
	$('#imovel_bairro_id').append($("<option></option>").attr("value",<%= bairro.id %>).text("<%= escape_javascript(bairro.nome) %>"));

<% end %>
$('#imovel_bairro_id').change();

app/views/imovels/dynamic_cidades.js.erb
$('#imovel_cidade_id').empty();
<% for cidade in @cidades %>
	
	$('#imovel_cidade_id').append($("<option></option>").attr("value",<%= cidade.id %>).text('<%= escape_javascript(cidade.nome) %>'));

<% end %>
$('#imovel_cidade_id').change();

app/views/imovels/edit.html.erb
<h1>Editing imovel</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @imovel %> |
<%= link_to 'Voltar', imovels_path %>

app/views/imovels/index.html.erb
<h1>Listando Imoveis</h1>
<br />

<table class="table table-condensed">
  <thead>
	  <tr>
	  	<th>Titulo</th>
	    <th>Cidade</th>
	    <th>Bairro</th>
	    <th>Tipo</th>
	    <th>Pretensao</th>
	    <th>Situacao</th>
	    <th>Area</th>
	    <th>Valor</th>
	    <th>Descricao</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
  </thead>

<% @imovels.each do |imovel| %>
  <tbody>
	  <tr>
	  	<td><%= imovel.titulo %></td>
	    <td><%= imovel.cidade %></td>
	    <td><%= imovel.bairro %></td>
	    <td><%= imovel.tipo %></td>
	    <td><%= imovel.pretensao %></td>
	    <td><%= imovel.situacao %></td>
	    <td><%= imovel.area %></td>
	    <td><%= imovel.valor %></td>
	    <td><%= imovel.descricao %></td>
	    <td><%= link_to 'Visualizar', imovel %></td>
	    <td><%= link_to 'Editar', edit_imovel_path(imovel) %></td>
	    <td><%= link_to 'Excluir', imovel, confirm: 'Você tem certeza?', method: :delete %></td>
	  </tr>
  </tbody>
<% end %>
</table>

<br />

<%= link_to 'Novo Imovel', new_imovel_path %>

app/views/imovels/new.html.erb
<div class="page-header">
	<h1>Novo Imóvel</h1>
</div>

<%= render 'form' %>

<%= link_to 'Voltar', imovels_path %>

app/views/imovels/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="span2">
		<%= render 'show_attrs' %>
	</div>
	<div class="span10">
		<%= render 'show_gallery' %>
	</div>
</div>

<%= link_to 'Editar', edit_imovel_path(@imovel) %> |
<%= link_to 'Voltar', imovels_path %>