config/routes.rb
Anunciar2::Application.routes.draw do
  resources :banners

  resources :imagems

  resources :imovels

  devise_for :users
  
  match 'imovels/dynamic_cidades/:id' => 'imovels#dynamic_cidades'
  match 'imovels/dynamic_bairros/:id' => 'imovels#dynamic_bairros'
  

  root :to => 'home#index'

end

app/views/layouts/_carousel.html.erb
<div id="myCarousel" class="carousel slide">
    <!-- Carousel items -->
    <div class="carousel-inner">
    	<% @banners.each.with_index do |b,index|%>
    		<div class="<%= "active" if index==1 %> item">
			    <div class="row-fluid">
			    	<div class="span1"></div>
			    	<div class="span7">
			    		<h2><%= b.imovel.titulo %></h2>
			            <p>
			            	<%= b.imovel.descricao %>
			            </p>
			            <p class="readmore">
			            	<%= link_to 'Ver Imóvel...', b.imovel %> &raquo;
			            </p>
			    	</div>
			    	<div class="span4 pull-right">
			    		<%= image_tag get_imovel_capa_url(b.imovel), :alt => '' %>
			    	</div>
			    </div>
	    	</div>
    	<%end%>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/layouts/_import.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</a>
<a class="brand" href="#">MeuImovelPB</a>
<div class="container nav-collapse">
	<ul class="nav pull-right">
		<li><%= link_to 'Home', '/' %></li>
		<% if user_signed_in? %>
		    <li><%= link_to 'Editar conta', edit_user_registration_path %></li>
		    <% if current_user.has_role? 'announcer' %>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						Gerenciar
						<b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to 'Meus Imoveis', imovels_path %></li>
						<li><%= link_to 'Novo Imovel', new_imovel_path %></li>
						<li><%= link_to 'Minhas Imagens', imagems_path %></li>
						<li><%= link_to 'Nova Imagem', new_imagem_path %></li>
						<% if current_user.has_role? 'admin' or current_user.has_role? 'root' %>
							<li><%= link_to 'Banners', banners_path %></li>
						<% end %>
					</ul>
				</li>
				<li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
			<% end %>
		<% else %>
			<li><%= link_to 'Login', new_user_session_path %></li>
			<li><%= link_to 'Cadastrar', new_user_registration_path %></li>
		<% end %>
	</ul>
</div><!--/.nav-collapse -->

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
	<h3>Sidebar</h3>
	<ul class="nav nav-list">
	  <li class="nav-header">Sidebar</li>
	  <li><%= link_to "Link1", "/path1"  %></li>
	  <li><%= link_to "Link2", "/path2"  %></li>
	  <li><%= link_to "Link3", "/path3"  %></li>
	</ul>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MeuImovelPB" %></title>
    <%= csrf_meta_tags %>
    
    <%= render 'layouts/import'%>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
        	<%= render 'layouts/navigation'%>
        </div>
      </div>
    </div>
    <div class="container">
    	<div class="content">
    		<div class="row">
    			<div class="span9">
	            	<%= render 'layouts/carousel' %>
	            </div>
	            <div class="span3">
	            	<%= render 'layouts/sidebar'%>
	            </div><!--/span-->
    		</div>
    	</div>
    	<br clear="all">
    	<div class="content">
	        <div class="row">
	            <div class="span12">
	            	<%= render 'layouts/messages'%>
	            	<%if params[:controller].include? 'devise' %>
	            		<div class="span6 offset3" >
	            			<%= yield %>
	            		</div>
	            	<%else%>
	            		<%= yield %>
	            	<%end%>
	            </div><!--/span-->
	        </div><!--/row-->
        </div><!--/content-->
        <br clear="all">
        <footer>
			<div class="nav">
				<div class="navbar-inner">
					<div class="container">
						<p>&copy; Company 2012</p>
						<a class="brand" href="#">MeuImovelPB</a>
					</div>
				</div>
			</div>
		</footer>
    </div> <!-- /container -->
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>